### ISSUE TITLE
nieustandaryzowane nazwy klas

### ISSUE THREAD

**Issue by 84lukaszkaminski** [infoshareacademy/jfdzw1-ipmdotdev#7]
Ustandaryzujcie sposób nazewnictwa klas. Po polsku albo po angielsku. Nie mieszajcie języków. To samo z rozdzielaniem słów. Najczęstszą praktyka jest używanie myślnika (some-class-name-with-many-words-does-not-make-any-problem-until-has-sense-and-describes-object; nie bójcie się opisowych, nawet długich nazw klas). 
Do ustandaryzowania możecie podejść dwojako:
- wyznaczyć osobę, która określi standard
- wypracujecie to wspólnie
Co jest pewne, jak chcecie dodać nowy kod do projektu, to najpierw zobaczcie jakie panują w nich zasady i się tego trzymajcie.

**Comment by burzykovski** [comment]
Zrobione. 
Nazwy klas po angielsku.
Oddzielanie-słów-myślnikami.
Rozbudowanie nazw tak aby wiadomo było o co chodzi.
