### ISSUE TITLE
podczas scrollowania menu jest zasłaniane przez hero-header-box

### ISSUE THREAD

**Issue by 84lukaszkaminski** [infoshareacademy/jfdzw1-ipmdotdev#8]
https://github.com/infoshareacademy/jfdzw1-ipmdotdev/blob/fa37dd8cfac7e3cbb0262b6a4a37134a1db8e429/index.html#L14

sprawdź [z-index](https://www.w3schools.com/cssref/pr_pos_z-index.asp)

**Comment by burzykovski** [comment]
Zrobione!
